# Generated by Django 5.0.2 on 2024-02-26 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portugues', models.PositiveIntegerField()),
                ('matematica', models.PositiveIntegerField()),
                ('historia', models.PositiveIntegerField()),
                ('geografia', models.PositiveIntegerField()),
                ('ciencias', models.PositiveIntegerField()),
                ('faltas', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_borrow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
