# Generated by Django 5.0.2 on 2024-02-26 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletim', '0003_relatorio_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to=settings.AUTH_USER_MODEL),
        ),
    ]
